base_url = "https://blog.dewstack.dev"
theme = "tabi"
title = "~/dewstack"
author = "Adam Dew"
generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = true
default_language = "en"

taxonomies = [{name = "tags", feed = true}]

[markdown]
highlight_code = true
highlight_theme = "css"


[search]
# Whether to include the title of the page/section in the index.
include_title = true
# Whether to include the description of the page/section in the index.
include_description = true
# Whether to include the path of the page/section in the index.
include_path = true
# Whether to include the rendered content of the page/section in the index.
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100
# Whether to produce the search index as a javascript file or as a JSON file.
# Accepted value "elasticlunr_javascript" or "elasticlunr_json".
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here


menu = [
    { name = "blog", url = "/blog", trailing_slash = true },
]


socials = [
    { name = "github", url = "https://github.com/adamdew/", icon = "github" },
]
